### ISSUE TITLE
GPTJ and MPT models - improve default promp size to match tokens size

### ISSUE THREAD

**Issue by overcrash66** [morph-labs/rift#128]
![Screenshot 2023-08-08 221039](https://github.com/morph-labs/rift/assets/3681221/59389782-a4ed-42d8-98da-6b329330b36c)
![GPT-j](https://github.com/morph-labs/rift/assets/3681221/a66880ca-14ef-4354-a256-716dee9e357a)

**Comment by jesse-michael-han** [comment]
Hello! Thanks for flagging this. This should now be fixed with #141 for Rift Chat --- gpt4all models now use the same truncation utilities as in `rift.llm.openai_client`.
