### ISSUE TITLE
bash reinstall.sh fails due to missing vsce and code

### ISSUE THREAD

**Issue by bobtista** [morph-labs/rift#133]
Errors I noticed:
reinstall.sh: line 18: vsce: command not found
reinstall.sh: line 22: code: command not found

Steps taken to fix:
brew install vsce
Open VS Code, shift+cmd+p, "Shell command: install 'code' command in PATH"
re-run bash reinstall.sh

**Comment by jesse-michael-han** [comment]
Thanks for pointing this out! Maybe you could make a PR adding these steps to the README?

**Comment by cristianoc** [comment]
`vsce` should probably be added to `package.json` to avoid extra install instructions.

**Comment by jesse-michael-han** [comment]
`@vscode/vsce` has now been added to `package.json` as of #141 . note that `vsce` may not be on your path so invocations of `vsce` may have to be replaced by `npm exec -- @vscode/vsce ...`
