### ISSUE TITLE
unset API key

### ISSUE THREAD

**Issue by Shawful** [morph-labs/rift#150]
I didn't see any documentation on what value I need to set for what I'm assuming is my OpenAI API key.  

Would someone please provide some clarity so that others may avoid the following error?

![image](https://github.com/morph-labs/rift/assets/5322272/896f783e-ae7c-4e44-b91e-7f2f885aacd7)

**Comment by Shawful** [comment]
After digging into the repo (5 minutes of my life and I'm happier for it :)) I found the following variable `OPENAI_API_KEY=sk-xxx`.  So this will resolve the issue for me, but I would add it to the documentation for anyone who uses the VSCode extension.  If I have time, I'll create a PR. 💯

**Comment by jesse-michael-han** [comment]
thanks for flagging this! resolved in https://github.com/morph-labs/rift/pull/154
