### ISSUE TITLE
Bug: Reset chat doesn't work

### ISSUE THREAD

**Issue by NarHakobyan** [morph-labs/rift#155]
<img width="490" alt="image" src="https://github.com/morph-labs/rift/assets/1781506/bdb84398-cf4c-4897-b59e-f7de2e7c0086">

**Comment by jesse-michael-han** [comment]
Thanks for flagging! Fixed in https://github.com/morph-labs/rift/commit/3820a58b03c983eb6449686cd0255de179a4ea41
