### ISSUE TITLE
Bug: if the file was sent as a first message then AI doesn't see it

### ISSUE THREAD

**Issue by NarHakobyan** [morph-labs/rift#156]
<img width="448" alt="image" src="https://github.com/morph-labs/rift/assets/1781506/f43b4384-a6dc-4698-aa69-f51b49a34fff">

**Comment by jesse-michael-han** [comment]
Thanks for flagging! Fixed in https://github.com/morph-labs/rift/commit/903ae284baf3ff9033c91cef931c31a40f9380a0

![image](https://github.com/morph-labs/rift/assets/39395247/f12140f3-2661-4a72-b58f-1fbf40624e31)
