### ISSUE TITLE
Support LocalAI models.

### ISSUE THREAD

**Issue by EdAyers** [morph-labs/rift#19]
[LocalAI](https://github.com/go-skynet/LocalAI) replicate the OpenAI api, so we should support setting arbitrary OpenAI URLs in the model configuration settings.

**Comment by karol-depka** [comment]
Nice!
Another way to phrase this title to make it more generic? 
"Add support for custom OpenAI URL(s), e.g. for LocalAI / OpenRouter.ai / Azure ."

I can take this task.

**Comment by karol-depka** [comment]
Added vscode config option stub

**Comment by karol-depka** [comment]
I should probably open a new issue for the VSCode config option

**Comment by karol-depka** [comment]
VSCode config option: https://github.com/morph-labs/rift/issues/231
