### ISSUE TITLE
Sublime Text support for Rift

### ISSUE THREAD

**Issue by jesse-michael-han** [morph-labs/rift#20]
Attempting to start the server from the Sublime Text LSP plugin results in the error `No implementation of ofdict for Literal`.

https://discord.com/channels/1117623339456933940/1122338689067012216/1122338710143381605

**Comment by jeremylan** [comment]
This is connected to [this issue](https://github.com/morph-labs/rift/issues/22)

**Comment by EdAyers** [comment]
This is now fixed
