### ISSUE TITLE
Why custom configuration handling?

### ISSUE THREAD

**Issue by rchl** [morph-labs/rift#22]
It seems like the server uses a custom `morph/set_model_config`request for sending configuration from the editor.

Maybe I'm missing something after skimming through the code but I wonder why it's using a custom request and not a standard [workspace/didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) and [workspace/configuration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) functionality?

Using a standard LSP functionality would work in all LSP-conforming client implementations while custom requests need some extra code.

**Comment by EdAyers** [comment]
thanks that's a good spot, I'll fix
