### ISSUE TITLE
Broken Pipe - a bug in the RPC server code

### ISSUE THREAD

**Issue by awatson1978** [morph-labs/rift#222]
Hello,
Trying to give Rift a try.  Have some parts of it installed and running, but unclear what's breaking here.  The server sort of tries to run:

<img width="1284" alt="Screenshot 2023-10-10 at 2 16 39 PM" src="https://github.com/morph-labs/rift/assets/675910/e57593e7-7d46-44b4-b147-9c1ef447d6a8">

The extension is loaded.  An OpenAI API key is added.  But not much showing up in the chat window.  

<img width="1718" alt="Screenshot 2023-10-10 at 2 18 52 PM" src="https://github.com/morph-labs/rift/assets/675910/ff8fdb2f-d7c6-45c5-8180-cd932edd922c">

Got any ideas what might be going on?

**Comment by jesse-michael-han** [comment]
hello! if you're starting the server yourself in a terminal, try setting rift.autostart to off and making sure you can connect to localhost:7797 via TCP

**Comment by awatson1978** [comment]
Okay, think I found the issue.  This was related to an arm64 architecture, and resolved by re-installing Python3 with arm64 patch support in `v3.10.13`.

```
$ arch 
arm64

$ which brew 
/opt/homebrew/bin/brew 

$ brew --version 
Homebrew 3.1.11 
Homebrew/homebrew-core (git revision 7c34424687; last commit 2021-06-10) 
Homebrew/homebrew-cask (git revision ab9a64f927; last commit 2021-06-10) 

$ pyenv --version 
pyenv 2.0.1-3-g1706436f

$ brew install openssl readline sqlite3 xz zlib

$ pyenv install 3.10.13

$ pyenv global 3.10.13
$ python --version

$ mkdir ~/.morph/ && cd ~/.morph/ && python -m venv env
$ source ./env/bin/activate

$ which pip
$ pip install --upgrade pyrift
$ pip install "git+https://github.com/morph-labs/rift.git@ea0ee39bd86c331616bdaf3e8c02ed7c913b0933#egg=pyrift&subdirectory=rift-engine"

$ cd ~/.morph/
$ git clone https://github.com/morph-labs/rift

$ cd ./rift
$ chmod +x full_install.sh
$ ./full_install.sh

$ cd rift-engine
$ pip install .
```
