### ISSUE TITLE
nice idea, not there yet? 

### ISSUE THREAD

**Issue by bayeslearner** [morph-labs/rift#230]
Been playing with it a couple of times now.  Saw its potential but seems very buggy.  
1. sometimes it simply stops responding, and I have to quit vscode to  reopen it. 
2. sometimes it cuts off from outputing the code: 
<img width="558" alt="image" src="https://github.com/morph-labs/rift/assets/68746303/b553f0f3-0195-4cea-b61a-b0cd8e670337">
3. sometimes it asks me to "add" files to context, but it doesn't show the prompts to do so.

**Comment by jesse-michael-han** [comment]
thanks for the feedback! we are working on a major refactor to address these sorts of performance issues, please join our Discord for updates: https://discord.gg/wa5sgWMfqv
