### ISSUE TITLE
Is that possible to use openai api?

### ISSUE THREAD

**Issue by TheCutestCat** [morph-labs/rift#4]
I see you wrote Openai API in the features. Can we use it on the Vscode?
My laptop is still struggling to run large language models locally, that will be a lot easier to use the API..

**Comment by jwd-dev** [comment]
yes, press Ctrl + , to get to the settings window then search Rift, then change model type and chat model type to openai and the model names to gpt-3.5-turbo

**Comment by jwd-dev** [comment]
I will add this to the readme somewhere, it's not obvious.

**Comment by TheCutestCat** [comment]
thanks, I found that @jwd-dev
