### ISSUE TITLE
VSCE issue

### ISSUE THREAD

**Issue by 3pillardeveloper** [morph-labs/rift#44]
I am trying to build the VS Code extension with the [following guide](https://github.com/morph-labs/rift#getting-started) but got stuck on this command in Powershell 5:

```ps1
PS C:\Users\REDACTED\source\repos\rift> vsce package .\editors\rift-vscode\
 ERROR  Extension manifest not found: C:\Users\REDACTED\source\repos\rift\package.json

PS C:\Users\REDACTED\source\repos\rift> cd .\editors\rift-vscode\
PS C:\Users\REDACTED\source\repos\rift> vsce package .
Executing prepublish script 'npm run vscode:prepublish'...

> rift-vscode@0.0.8 vscode:prepublish
> npm run compile

> rift-vscode@0.0.8 compile
> node ./build.mjs

  out\main.js      828.0kb
  out\main.js.map    1.5mb

⚡ Done in 62ms
 ERROR  Invalid version .
```

Searching online I found out that VS Code extensions need "engines.vscode" specified in the `package.json`:

```diff
{
  ...
+  "engines": {
+    "vscode": "^1.7.5"
+  }
 ...
}
```

I re-ran the command above but still no cigar.

**Comment by jesse-michael-han** [comment]
Hey @3pillardeveloper, this was my bad --- the instructions were incorrect and made faulty assumptions about how `vsce` works. I just opened https://github.com/morph-labs/rift/pull/63 which should work and hopefully unblocks you. Thanks for flagging this!
