### ISSUE TITLE
CPU usage continues after a completion is cancelled (by clicking on `running`)

### ISSUE THREAD

**Issue by cristianoc** [morph-labs/rift#5]
When a cancellation event occurs, the underlying streaming process associated with TextStream and GPT4ALL Model continues to run and consume CPU resources until the model has finished. This behavior is undesirable, as it leads to unnecessary resource utilization, and can negatively impact system performance. The streaming process should halt its operation immediately upon receiving a cancellation event to free up system resources.
[written by AI of course]

**Comment by jesse-michael-han** [comment]
yeehaw #6
