### ISSUE TITLE
Error while using Rift (OpenAI key is missing)

### ISSUE THREAD

**Issue by moshere** [morph-labs/rift#55]
Hi,
I installed rift engine on my local machine.
Running the extension, got the following error in the server

```
<LspServer 1> transport closed gracefully: end of stream                                                                                jsonrpc.py:541
           INFO     exiting serve_forever loop                                                                                                              jsonrpc.py:569
           INFO     <LspServer 1> entered shutdown state                                                                                                    jsonrpc.py:584
           INFO     initializing LSP server <LspServer 2>                                                                                                     server.py:47
           INFO     client initialized.                                                                                                                       server.py:55
[18:46:12] INFO     <LspServer 2> recieved model config chatModel='openai:gpt-3.5-turbo' completionsModel='openai:gpt-3.5-turbo' openaiKey=None                 lsp.py:249
           ERROR    <LspServer 2> request morph/run_chat:1 unhandled ValidationError:                                                                       jsonrpc.py:648
                    1 validation error for OpenAIClient   
```                       
Full error: https://pastebin.com/HmzBTuMW

Why it's looking for OpenAI key? I thought this is local LLM model that deal with Copilot without the need for OpenAI

**Comment by jeremylan** [comment]
@moshere the default model is `openai:gpt-3.5-turbo` which requires an OpenAI API Key.
If you want a local model, go to `Settings` in VS.Code, search for `Rift` and change the `Chat Model` and the `Completions Model` to a `gpt4all` one. Restart the server and Rift will install the local model.

**Comment by moshere** [comment]
Thanks a lot @jeremylan. Could connect to the local model however get only jibrish responses.
Is there any additional configuration I need to do?

<img width="1031" alt="image" src="https://github.com/morph-labs/rift/assets/7210322/63872a91-9134-46b7-811f-e3f7f166ddbb">

**Comment by jesse-michael-han** [comment]
That might be a prompting error. If you are running the models locally, you should check that the `chatModel` has been set to a model that has been trained on chat data, such as `mpt` or `ggml-gptj-groovy`.

I would recommend stopping by the Discord and creating a thread in the rift-support channel where we can help synchronously.

**Comment by moshere** [comment]
thank you. I've been able to resolve it while using this setup
<img width="842" alt="image" src="https://github.com/morph-labs/rift/assets/7210322/2f68c9c8-93cd-4582-9812-acde1264be5f">
