### ISSUE TITLE
Rift Agents: add support for `gpt-engineer`

### ISSUE THREAD

**Issue by jesse-michael-han** [morph-labs/rift#67]
We should add support for `gpt-engineer` in `rift.agents`. This would involve:

1. creating `rift-engine/rift/agents/gpt_engineer.py`
2. implementing a `GPTEngineer` instance of `Agent`
3. Refactoring the main running logic of `Step` objects in the `gpt-engineer` library so that we can emit batches of `file_diff.FileChange`s in the implementation of `Agent.run()`.

**Comment by jesse-michael-han** [comment]
Once we implement #62 we'll be able to connect multiple such agents to a single LSPServer instance.

**Comment by jwd-dev** [comment]
Do we want to implement streaming? Right now the files are updated after the streaming event is complete. 
````
response = openai.ChatCompletion.create(
            messages=messages,
            stream=True,
            model=self.model,
            temperature=self.temperature,
        )

        chat = []
        for chunk in response:
            delta = chunk["choices"][0]["delta"]  # type: ignore
            msg = delta.get("content", "")
            print(msg, end="")
            chat.append(msg)

**Comment by jesse-michael-han** [comment]
does the VSCode refactor UI support streaming / incrementally updated file diffs? my guess was no which is why we should wait

the point of having `Agent.run()` be an async iterable is so that the agent can stream in batches of changes when they're ready, but in this case I think it should be all at once since it's generating a bunch of code files in one go.
