### ISSUE TITLE
No pytorch error

### ISSUE THREAD

**Issue by fardeem** [morph-labs/rift#9]
Amazing project! I tried running it and running into this issue:

On Python 3.11.4. pip 22.3.1

<img width="984" alt="image" src="https://github.com/morph-labs/rift/assets/2018374/54df1343-99b8-42f8-a14f-25ad39d2e9d8">

**Comment by EdAyers** [comment]
This is the `transformers` library, we only use it for the tokenizer so we don't load up any of the above libraries. I'll look into getting this turned off.

**Comment by jesse-michael-han** [comment]
We'll need the frameworks to run inference out of the box for the HuggingFace models in the `hf` codepath. Maybe we can add them as an optional dependency?

**Comment by EdAyers** [comment]
yes it's currently an optional dependency
